# Generated by Django 4.1.6 on 2024-04-23 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentRegistration",
            new_name="Studen",
        ),
    ]
